<a href="https://colab.research.google.com/github/VennyA/crm-revops-analytics-/blob/main/CRM_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
import pandas as pd

churn = pd.read_csv('/content/drive/MyDrive/CRM PROJECT/crm_churn.csv')
companies = pd.read_csv('/content/drive/MyDrive/CRM PROJECT/crm_companies.csv')
customers = pd.read_csv('/content/drive/MyDrive/CRM PROJECT/crm_customers.csv')
deals = pd.read_csv('/content/drive/MyDrive/CRM PROJECT/crm_deals.csv')
leads = pd.read_csv('/content/drive/MyDrive/CRM PROJECT/crm_leads.csv')
pricing = pd.read_csv('/content/drive/MyDrive/CRM PROJECT/crm_pricing.csv')
buyer=pd.read_csv('/content/drive/MyDrive/CRM PROJECT/crm_buyer_evidence.csv')

In [3]:
for name, df in {
    'churn': churn,
    'companies': companies,
    'customers': customers,
    'deals': deals,
    'leads': leads,
    'pricing': pricing,
    'buyer' :buyer
}.items():
    print(f"\n{name.upper()}")
    print(df.shape)
    print(df.columns.tolist())

CHURN
(207, 14)
['churn_id', 'customer_id', 'churned', 'churn_date', 'churn_reason', 'days_to_churn', 'churn_type', 'refund_issued', 'refund_amount_usd', 'exit_survey_completed', 'win_back_attempted', 'win_back_successful', 'final_mrr_usd', 'churned_arr_usd']

COMPANIES
(8811, 18)
['company_id', 'company_name', 'website', 'linkedin_url', 'industry', 'company_type', 'company_size', 'number_of_employees', 'annual_revenue_usd', 'region', 'country', 'primary_contact_title', 'tech_stack', 'lifecycle_stage', 'lead_status', 'date_added', 'last_activity_date', 'notes']

CUSTOMERS
(871, 21)
['customer_id', 'lead_id', 'contract_start_date', 'contract_end_date', 'contract_length_months', 'product_usage_score', 'nps_score', 'mrr_usd', 'arr_usd', 'plan_tier', 'customer_success_rep', 'health_score', 'health_status', 'onboarding_status', 'support_tier', 'number_of_support_tickets', 'last_login_date', 'expansion_revenue_usd', 'referrals_made', 'renewal_date', 'auto_renew']

DEALS
(1659, 18)
['deal_id', 'lead_id', 'plan_tier', 'plan_id', 'deal_value_annual_usd', 'close_date', 'loss_reason', 'deal_stage', 'deal_probability_pct', 'deal_type', 'deal_currency', 'expected_close_date', 'weighted_value_usd', 'number_of_contacts', 'competitor', 'discount_pct', 'contract_type', 'next_step']

LEADS
(10180, 25)
['lead_id', 'company_id', 'contact_name', 'contact_email', 'created_date', 'lead_source', 'assigned_rep', 'funnel_stage', 'days_lead_to_mql', 'days_mql_to_sql', 'days_sql_to_opportunity', 'days_opportunity_to_close', 'lead_score', 'lead_status', 'last_contacted_date', 'number_of_contacts', 'last_contact_method', 'sdr_owner', 'utm_source', 'utm_medium', 'utm_campaign', 'email_opt_in', 'phone_number', 'job_title', 'notes']

PRICING
(4, 22)
['plan_id', 'plan_name', 'plan_tier_key', 'price_per_seat_monthly_usd', 'price_per_seat_annual_usd', 'min_seats', 'max_seats', 'billing_cycle', 'free_trial_days', 'features_crm', 'features_analytics', 'features_automation', 'features_api_access', 'features_sso', 'features_dedicated_csm', 'features_custom_integrations', 'support_type', 'onboarding_included', 'sla_uptime_pct', 'plan_launched_date', 'plan_status', 'notes']

BUYER
(1659, 11)
['evidence_id', 'deal_id', 'last_confirmed_buyer_response_date', 'authority_engaged', 'business_problem_confirmed', 'consequence_confirmed', 'decision_timing_reconfirmed', 'buyer_owned_next_step', 'next_step_date', 'next_step_owner', 'buyer_evidence_score']

In [4]:
print("companies.company_id:", companies['company_id'].is_unique)
print("leads.lead_id:", leads['lead_id'].is_unique)
print("customers.customer_id:", customers['customer_id'].is_unique)
print("pricing.plan_id:", pricing['plan_id'].is_unique)
print("deals.deal_id:", deals['deal_id'].is_unique)
print("churn.churn_id:", churn['churn_id'].is_unique)
print("buyer.evidence_id", buyer['evidence_id'].is_unique)

companies.company_id: True
leads.lead_id: True
customers.customer_id: True
pricing.plan_id: True
deals.deal_id: True
churn.churn_id: True
buyer.evidence_id True

In [5]:
print(leads['company_id'].isin(companies['company_id']).mean())
print(customers['lead_id'].isin(leads['lead_id']).mean())
print(deals['lead_id'].isin(leads['lead_id']).mean())
print(churn['customer_id'].isin(customers['customer_id']).mean())
print(deals['plan_id'].isin(pricing['plan_id']).mean())
print(buyer['deal_id'].isin(deals['deal_id']).mean())

1.0
1.0
1.0
1.0
1.0
1.0

In [6]:
print(companies['company_id'].is_unique)
print(leads['company_id'].is_unique)
print(customers['lead_id'].is_unique)
print(leads['lead_id'].is_unique)
print(deals['lead_id'].is_unique)
print(leads['lead_id'].is_unique)
print(customers['customer_id'].is_unique)
print(churn['customer_id'].is_unique)
print(pricing['plan_id'].is_unique)
print(deals['plan_id'].is_unique)
print(buyer['deal_id'].is_unique)
print(deals['deal_id'].is_unique)

True
False
True
True
True
True
True
True
True
False
True
True

In [7]:
for name, df in {
    'churn': churn,
    'companies': companies,
    'customers': customers,
    'deals': deals,
    'leads': leads,
    'pricing': pricing,
    'buyer': buyer
}.items():
    print(f'\n{name.upper()}')
    print(df.isnull().sum().sort_values(ascending=False).head(10))

CHURN
churn_id                 0
customer_id              0
churned                  0
churn_date               0
churn_reason             0
days_to_churn            0
churn_type               0
refund_issued            0
refund_amount_usd        0
exit_survey_completed    0
dtype: int64

COMPANIES
notes                 5828
annual_revenue_usd     438
company_size           438
industry               267
region                  84
company_id               0
company_name             0
company_type             0
website                  0
linkedin_url             0
dtype: int64

CUSTOMERS
plan_tier                 45
lead_id                    0
contract_start_date        0
contract_end_date          0
customer_id                0
contract_length_months     0
product_usage_score        0
mrr_usd                    0
nps_score                  0
arr_usd                    0
dtype: int64

DEALS
loss_reason              826
competitor               415
next_step                363
deal_value_annual_usd     49
lead_id                    0
deal_id                    0
close_date                 0
deal_stage                 0
plan_id                    0
plan_tier                  0
dtype: int64

LEADS
days_sql_to_opportunity      8439
days_opportunity_to_close    8439
notes                        8122
days_mql_to_sql              7165
days_lead_to_mql             4894
phone_number                 2588
utm_medium                   1419
utm_campaign                 1407
last_contact_method          1352
utm_source                   1257
dtype: int64

PRICING
max_seats                     1
plan_id                       0
plan_tier_key                 0
price_per_seat_monthly_usd    0
price_per_seat_annual_usd     0
plan_name                     0
min_seats                     0
billing_cycle                 0
free_trial_days               0
features_crm                  0
dtype: int64

BUYER
next_step_owner                       175
buyer_owned_next_step                 175
evidence_id                             0
last_confirmed_buyer_response_date      0
deal_id                                 0
authority_engaged                       0
business_problem_confirmed              0
decision_timing_reconfirmed             0
consequence_confirmed                   0
next_step_date                          0
dtype: int64

In [8]:
companies[companies['company_size'].isnull() & companies['annual_revenue_usd'].isnull()].shape

(438, 18)

In [9]:
print(leads.duplicated().sum())
print(churn.duplicated().sum())
print(companies.duplicated().sum())
print(deals.duplicated().sum())
print(pricing.duplicated().sum())
print(customers.duplicated().sum())
print(buyer.duplicated().sum())

0
0
0
0
0
0
0

In [10]:
leads.duplicated(
    subset=['contact_name', 'contact_email', 'company_id']
).sum()

np.int64(125)

In [11]:
leads[
    leads.duplicated(
        subset=['contact_name', 'contact_email', 'company_id'],
        keep=False
    )
].sort_values(['contact_email', 'company_id'])

,lead_id,company_id,contact_name,contact_email,created_date,lead_source,assigned_rep,funnel_stage,days_lead_to_mql,days_mql_to_sql,...,number_of_contacts,last_contact_method,sdr_owner,utm_source,utm_medium,utm_campaign,email_opt_in,phone_number,job_title,notes
3271,LEAD-08974,COMP-03070,Andrea Morales,ajones@morgan.com,2024-06-10,Content Download,Jeffrey Stanley,SQL,4.0,4.0,...,7,LinkedIn,Elizabeth Jordan,linkedin,NaN,product_launch,True,NaN,Illustrator,NaN
9170,LEAD-08974-DUP,COMP-03070,Andrea Morales,ajones@morgan.com,"Jun 14, 2024",content download,Jeffrey Stanley,SQL,4.0,4.0,...,10,Email,Suzanne Leach,email,email,newsletter,True,001-441-386-9899x63702,Contractor,NaN
8227,LEAD-04838,COMP-07237,Shelly Hammond,alexandriakennedy@terrell.net,2022-06-22,Organic Search,Ryan Carter,SQL,3.0,7.0,...,3,LinkedIn,Elizabeth Jordan,direct,organic,brand_awareness,True,7526445056,Museum education officer,NaN
9675,LEAD-04838-DUP,COMP-07237,Shelly Hammond,alexandriakennedy@terrell.net,2022-06-27,organic search,Ryan Carter,SQL,3.0,7.0,...,1,Email,Elizabeth Jordan,facebook,banner,demo_request,True,233.973.5553x78157,Best boy,NaN
728,LEAD-05292-DUP,COMP-00721,Brittney Welch,anne02@gardner-davies.info,"Mar 08, 2023",Webinar,Ryan Carter,marketing qualified lead,12.0,NaN,...,3,Phone,Emma Padilla,direct,social,demo_request,False,(227)687-1723x85526,"Editor, magazine features",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8702,LEAD-02526-DUP,COMP-05734,Susan Ho,xjarvis@mcbride-barnes.com,05/11/2022,Ref,Hunter Anderson,MQL,11.0,NaN,...,11,LinkedIn Message,Emma Padilla,linkedin,email,brand_awareness,True,(441)746-6294x48287,"Teacher, primary school",NaN
777,LEAD-05326,COMP-00769,Rachel Johnson,ymartinez@white.com,2022-03-16,trial,Hunter Anderson,MQL,1.0,NaN,...,8,Email,Nicholas Macdonald,email,organic,product_launch,False,908-357-7732x529,Environmental education officer,NaN
933,LEAD-05326-DUP,COMP-00769,Rachel Johnson,ymartinez@white.com,2022/03/19,trial,Hunter Anderson,MQL,1.0,NaN,...,14,Email,Elizabeth Jordan,direct,social,NaN,True,001-888-996-5611x3230,Cartographer,NaN
817,LEAD-09933-DUP,COMP-00808,Douglas Wright,zmoore@chandler.com,2024/11/26,Gated Content,Hunter Anderson,SQL,11.0,7.0,...,11,Email,Elizabeth Jordan,direct,banner,brand_awareness,True,478.403.5496x30057,Licensed conveyancer,NaN
7219,LEAD-09933,COMP-00808,Douglas Wright,zmoore@chandler.com,2024-11-21,Content Download,Hunter Anderson,SQL,11.0,7.0,...,1,NaN,Suzanne Leach,NaN,referral,q1_outbound,True,9417146504,Psychiatric nurse,NaN

In [12]:
leads = leads[~leads['lead_id'].str.contains('-DUP')]
print(leads.shape)

(10000, 25)

In [13]:
for name, df in {
    'churn': churn,
    'companies': companies,
    'customers': customers,
    'deals': deals,
    'leads': leads,
    'pricing': pricing,
    'buyer' : buyer
}.items():
    print(f"\n{name.upper()}")
    print(df.info())

CHURN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   churn_id               207 non-null    object
 1   customer_id            207 non-null    object
 2   churned                207 non-null    bool
 3   churn_date             207 non-null    object
 4   churn_reason           207 non-null    object
 5   days_to_churn          207 non-null    int64
 6   churn_type             207 non-null    object
 7   refund_issued          207 non-null    bool
 8   refund_amount_usd      207 non-null    float64
 9   exit_survey_completed  207 non-null    bool
 10  win_back_attempted     207 non-null    bool
 11  win_back_successful    207 non-null    bool
 12  final_mrr_usd          207 non-null    float64
 13  churned_arr_usd        207 non-null    float64
dtypes: bool(5), float64(3), int64(1), object(5)
memory usage: 15.7+ KB
None

COMPANIES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8811 entries, 0 to 8810
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company_id             8811 non-null   object
 1   company_name           8811 non-null   object
 2   website                8811 non-null   object
 3   linkedin_url           8811 non-null   object
 4   industry               8544 non-null   object
 5   company_type           8811 non-null   object
 6   company_size           8373 non-null   object
 7   number_of_employees    8811 non-null   int64
 8   annual_revenue_usd     8373 non-null   float64
 9   region                 8727 non-null   object
 10  country                8811 non-null   object
 11  primary_contact_title  8811 non-null   object
 12  tech_stack             8811 non-null   object
 13  lifecycle_stage        8811 non-null   object
 14  lead_status            8811 non-null   object
 15  date_added             8811 non-null   object
 16  last_activity_date     8811 non-null   object
 17  notes                  2983 non-null   object
dtypes: float64(1), int64(1), object(16)
memory usage: 1.2+ MB
None

CUSTOMERS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871 entries, 0 to 870
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                871 non-null    object
 1   lead_id                    871 non-null    object
 2   contract_start_date        871 non-null    object
 3   contract_end_date          871 non-null    object
 4   contract_length_months     871 non-null    float64
 5   product_usage_score        871 non-null    float64
 6   nps_score                  871 non-null    float64
 7   mrr_usd                    871 non-null    float64
 8   arr_usd                    871 non-null    float64
 9   plan_tier                  826 non-null    object
 10  customer_success_rep       871 non-null    object
 11  health_score               871 non-null    int64
 12  health_status              871 non-null    object
 13  onboarding_status          871 non-null    object
 14  support_tier               871 non-null    object
 15  number_of_support_tickets  871 non-null    int64
 16  last_login_date            871 non-null    object
 17  expansion_revenue_usd      871 non-null    float64
 18  referrals_made             871 non-null    int64
 19  renewal_date               871 non-null    object
 20  auto_renew                 871 non-null    bool
dtypes: bool(1), float64(6), int64(3), object(11)
memory usage: 137.1+ KB
None

DEALS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   deal_id                1659 non-null   object
 1   lead_id                1659 non-null   object
 2   plan_tier              1659 non-null   object
 3   plan_id                1659 non-null   object
 4   deal_value_annual_usd  1610 non-null   float64
 5   close_date             1659 non-null   object
 6   loss_reason            833 non-null    object
 7   deal_stage             1659 non-null   object
 8   deal_probability_pct   1659 non-null   int64
 9   deal_type              1659 non-null   object
 10  deal_currency          1659 non-null   object
 11  expected_close_date    1659 non-null   object
 12  weighted_value_usd     1659 non-null   float64
 13  number_of_contacts     1659 non-null   int64
 14  competitor             1244 non-null   object
 15  discount_pct           1659 non-null   float64
 16  contract_type          1659 non-null   object
 17  next_step              1296 non-null   object
dtypes: float64(3), int64(2), object(13)
memory usage: 233.4+ KB
None

LEADS
<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10179
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   lead_id                    10000 non-null  object
 1   company_id                 10000 non-null  object
 2   contact_name               10000 non-null  object
 3   contact_email              10000 non-null  object
 4   created_date               10000 non-null  object
 5   lead_source                10000 non-null  object
 6   assigned_rep               9600 non-null   object
 7   funnel_stage               10000 non-null  object
 8   days_lead_to_mql           5106 non-null   float64
 9   days_mql_to_sql            2948 non-null   float64
 10  days_sql_to_opportunity    1741 non-null   float64
 11  days_opportunity_to_close  1741 non-null   float64
 12  lead_score                 10000 non-null  int64
 13  lead_status                10000 non-null  object
 14  last_contacted_date        10000 non-null  object
 15  number_of_contacts         10000 non-null  int64
 16  last_contact_method        8674 non-null   object
 17  sdr_owner                  10000 non-null  object
 18  utm_source                 8760 non-null   object
 19  utm_medium                 8599 non-null   object
 20  utm_campaign               8611 non-null   object
 21  email_opt_in               10000 non-null  bool
 22  phone_number               7460 non-null   object
 23  job_title                  10000 non-null  object
 24  notes                      2029 non-null   object
dtypes: bool(1), float64(4), int64(2), object(18)
memory usage: 1.9+ MB
None

PRICING
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 22 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   plan_id                       4 non-null      object
 1   plan_name                     4 non-null      object
 2   plan_tier_key                 4 non-null      object
 3   price_per_seat_monthly_usd    4 non-null      int64
 4   price_per_seat_annual_usd     4 non-null      int64
 5   min_seats                     4 non-null      int64
 6   max_seats                     3 non-null      float64
 7   billing_cycle                 4 non-null      object
 8   free_trial_days               4 non-null      int64
 9   features_crm                  4 non-null      bool
 10  features_analytics            4 non-null      bool
 11  features_automation           4 non-null      bool
 12  features_api_access           4 non-null      bool
 13  features_sso                  4 non-null      bool
 14  features_dedicated_csm        4 non-null      bool
 15  features_custom_integrations  4 non-null      bool
 16  support_type                  4 non-null      object
 17  onboarding_included           4 non-null      bool
 18  sla_uptime_pct                4 non-null      float64
 19  plan_launched_date            4 non-null      object
 20  plan_status                   4 non-null      object
 21  notes                         4 non-null      object
dtypes: bool(8), float64(2), int64(4), object(8)
memory usage: 612.0+ bytes
None

BUYER
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 11 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   evidence_id                         1659 non-null   object
 1   deal_id                             1659 non-null   object
 2   last_confirmed_buyer_response_date  1659 non-null   object
 3   authority_engaged                   1659 non-null   object
 4   business_problem_confirmed          1659 non-null   bool
 5   consequence_confirmed               1659 non-null   bool
 6   decision_timing_reconfirmed         1659 non-null   bool
 7   buyer_owned_next_step               1484 non-null   object
 8   next_step_date                      1659 non-null   object
 9   next_step_owner                     1484 non-null   object
 10  buyer_evidence_score                1659 non-null   int64
dtypes: bool(3), int64(1), object(7)
memory usage: 108.7+ KB
None

In [14]:
tables = {
    'churn': churn,
    'companies': companies,
    'customers': customers,
    'deals': deals,
    'leads': leads,
    'pricing': pricing,
    'buyer' : buyer
}

for table_name, df in tables.items():
    print(f"\n{table_name.upper()}")

    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        count = ((df[col] < lower) | (df[col] > upper)).sum()

        print(f"{col}: {count} outliers")

CHURN
days_to_churn: 6 outliers
refund_amount_usd: 37 outliers
final_mrr_usd: 20 outliers
churned_arr_usd: 20 outliers

COMPANIES
number_of_employees: 1200 outliers
annual_revenue_usd: 1300 outliers

CUSTOMERS
contract_length_months: 0 outliers
product_usage_score: 5 outliers
nps_score: 0 outliers
mrr_usd: 84 outliers
arr_usd: 84 outliers
health_score: 6 outliers
number_of_support_tickets: 0 outliers
expansion_revenue_usd: 194 outliers
referrals_made: 0 outliers

DEALS
deal_value_annual_usd: 340 outliers
deal_probability_pct: 0 outliers
weighted_value_usd: 287 outliers
number_of_contacts: 0 outliers
discount_pct: 5 outliers

LEADS
days_lead_to_mql: 0 outliers
days_mql_to_sql: 0 outliers
days_sql_to_opportunity: 0 outliers
days_opportunity_to_close: 0 outliers
lead_score: 0 outliers
number_of_contacts: 0 outliers

PRICING
price_per_seat_monthly_usd: 0 outliers
price_per_seat_annual_usd: 0 outliers
min_seats: 1 outliers
max_seats: 0 outliers
free_trial_days: 1 outliers
sla_uptime_pct: 0 outliers

BUYER
buyer_evidence_score: 0 outliers

In [15]:
deals[deals['deal_value_annual_usd'] < 0].count()

deal_id                  12
lead_id                  12
plan_tier                12
plan_id                  12
deal_value_annual_usd    12
close_date               12
loss_reason               7
deal_stage               12
deal_probability_pct     12
deal_type                12
deal_currency            12
expected_close_date      12
weighted_value_usd       12
number_of_contacts       12
competitor                9
discount_pct             12
contract_type            12
next_step                 9
dtype: int64

In [16]:
deals[deals['deal_value_annual_usd'] > 3000000]

,deal_id,lead_id,plan_tier,plan_id,deal_value_annual_usd,close_date,loss_reason,deal_stage,deal_probability_pct,deal_type,deal_currency,expected_close_date,weighted_value_usd,number_of_contacts,competitor,discount_pct,contract_type,next_step
1634,DEAL-01635,LEAD-04738,Growth,PLAN-002,5686737.0,2023-03-26,NaN,Closed Won,100,Expansion,USD,2023-03-26,5686737.0,7,Pipedrive,0.0,Monthly,NaN

In [17]:
customers[customers['product_usage_score'] > 100]

,customer_id,lead_id,contract_start_date,contract_end_date,contract_length_months,product_usage_score,nps_score,mrr_usd,arr_usd,plan_tier,...,health_score,health_status,onboarding_status,support_tier,number_of_support_tickets,last_login_date,expansion_revenue_usd,referrals_made,renewal_date,auto_renew
130,CUST-00131,LEAD-07037,2024-12-19,12/04/2027,36.0,150.0,5.0,6376.37,76516.44,Enterprise,...,85,Healthy,Complete,Enterprise,6,2026-01-28,0.00,2,12/04/2027,False
147,CUST-00148,LEAD-00186,"October 20, 2023",2024-10-14,12.0,101.0,10.0,1750.32,21003.84,Growth,...,66,Healthy,Complete,Standard,5,2025-12-01,0.00,4,2024-10-14,True
358,CUST-00359,LEAD-01437,29-09-2022,2023-09-24,12.0,200.0,0.0,9496.77,113961.24,Enterprise,...,110,Healthy,Complete,Enterprise,21,2025-10-21,0.00,5,2023-09-24,False
544,CUST-00545,LEAD-02410,"Aug 25, 2023",2026-08-09,36.0,200.0,1.0,4943.46,59321.52,NaN,...,102,Healthy,Complete,Standard,1,2024-08-18,0.00,4,2026-08-09,True
647,CUST-00648,LEAD-00573,20-05-2023,2024-05-14,12.0,200.0,6.0,2612.82,31353.84,NaN,...,112,Healthy,Complete,Standard,9,2024-08-01,7360.65,1,2024-05-14,False
685,CUST-00686,LEAD-08080,2025-02-08,2028/01/24,36.0,150.0,2.0,389.86,4678.32,Pro,...,79,Healthy,Complete,Premium,22,2025-04-16,0.00,2,2028/01/24,True
755,CUST-00756,LEAD-02354,10/07/2024,2025-07-05,12.0,200.0,10.0,1210.55,14526.60,Growth,...,118,Healthy,Complete,Standard,20,2025-09-26,0.00,1,2025-07-05,True
801,CUST-00802,LEAD-02191,2023-07-23,2025/07/12,24.0,200.0,1.0,7785.79,93429.48,Pro,...,103,Healthy,Complete,Premium,8,2023-11-18,0.00,3,2025/07/12,True

In [18]:
customers[customers['product_usage_score'] < 0]

,customer_id,lead_id,contract_start_date,contract_end_date,contract_length_months,product_usage_score,nps_score,mrr_usd,arr_usd,plan_tier,...,health_score,health_status,onboarding_status,support_tier,number_of_support_tickets,last_login_date,expansion_revenue_usd,referrals_made,renewal_date,auto_renew
183,CUST-00184,LEAD-05869,2023-11-01,2026-10-16,36.0,-5.0,10.0,11694.57,140334.84,Enterprise,...,12,Critical,Complete,Enterprise,23,2026-01-21,0.0,2,2026-10-16,True
655,CUST-00656,LEAD-08119,10/30/2024,2025-10-25,12.0,-5.0,7.0,4895.61,58747.32,NaN,...,10,Critical,In Progress,Standard,15,2026-01-21,0.0,0,2025-10-25,False

In [19]:
customers[customers['nps_score'] > 10]

,customer_id,lead_id,contract_start_date,contract_end_date,contract_length_months,product_usage_score,nps_score,mrr_usd,arr_usd,plan_tier,...,health_score,health_status,onboarding_status,support_tier,number_of_support_tickets,last_login_date,expansion_revenue_usd,referrals_made,renewal_date,auto_renew
53,CUST-00054,LEAD-02677,"Feb 17, 2024","Feb 06, 2026",24.0,44.0,11.0,782.93,9395.16,NaN,...,40,At Risk,Complete,Standard,1,2025-01-03,0.0,3,"Feb 06, 2026",True
299,CUST-00300,LEAD-03036,2022-06-21,2023/06/16,12.0,19.0,12.0,2102.61,25231.32,Growth,...,27,Critical,Complete,Standard,20,2022-06-29,0.0,2,2023/06/16,True
468,CUST-00469,LEAD-06454,2023-09-14,2024-09-08,12.0,87.0,15.0,2002.64,24031.68,Growth,...,66,Healthy,Not Started,Standard,21,2026-05-31,0.0,1,2024-09-08,False
471,CUST-00472,LEAD-05474,2022-04-03,2023-03-29,12.0,61.0,11.0,933.28,11199.36,Enterprise,...,47,At Risk,In Progress,Enterprise,17,2022-05-24,0.0,2,2023-03-29,False
526,CUST-00527,LEAD-02799,2024-08-10,2027-07-26,36.0,79.0,15.0,527.73,6332.76,Starter,...,62,At Risk,In Progress,Standard,5,2025-11-02,0.0,0,2027-07-26,True
536,CUST-00537,LEAD-05510,"January 01, 2025",2026-12-22,24.0,18.0,11.0,1241.49,14897.88,Growth,...,26,Critical,Not Started,Standard,5,2025-05-12,0.0,4,2026-12-22,True
556,CUST-00557,LEAD-07835,2024-04-24,2026-04-14,24.0,80.0,12.0,15356.68,184280.16,Enterprise,...,59,At Risk,Complete,Enterprise,8,2024-11-02,0.0,4,2026-04-14,True
637,CUST-00638,LEAD-08010,2024-04-12,"April 02, 2026",24.0,55.0,12.0,5207.65,62491.80,Pro,...,48,At Risk,Complete,Premium,1,2024-11-05,0.0,0,"April 02, 2026",False
760,CUST-00761,LEAD-00727,"Nov 30, 2023",2026-11-14,36.0,45.0,12.0,17831.03,213972.36,Enterprise,...,40,At Risk,Complete,Enterprise,15,2024-10-23,0.0,2,2026-11-14,False
802,CUST-00803,LEAD-01066,2024-08-25,2027-08-10,36.0,83.0,12.0,1278.40,15340.80,Growth,...,60,At Risk,Complete,Standard,14,2026-01-03,0.0,4,2027-08-10,False
845,CUST-00846,LEAD-02428,2024-03-22,2025-03-17,12.0,75.0,12.0,2862.64,34351.68,Growth,...,56,At Risk,Complete,Standard,4,2026-06-07,0.0,3,2025-03-17,False
862,CUST-00863,LEAD-04738,26-03-2023,2024-03-20,12.0,10.0,11.0,2291.88,27502.56,Growth,...,21,Critical,Not Started,Standard,10,2024-07-13,0.0,3,2024-03-20,True

In [20]:
customers[customers['nps_score'] < 0]

,customer_id,lead_id,contract_start_date,contract_end_date,contract_length_months,product_usage_score,nps_score,mrr_usd,arr_usd,plan_tier,...,health_score,health_status,onboarding_status,support_tier,number_of_support_tickets,last_login_date,expansion_revenue_usd,referrals_made,renewal_date,auto_renew
398,CUST-00399,LEAD-04232,2022-12-28,2025-12-12,36.0,60.0,-1.0,11238.77,134865.24,Enterprise,...,28,Critical,Complete,Enterprise,4,2025-02-06,0.00,0,2025-12-12,False
706,CUST-00707,LEAD-01383,"October 02, 2022",2024-09-21,24.0,43.0,-1.0,349.16,4189.92,Starter,...,22,Critical,Complete,Standard,21,2024-07-06,7484.54,3,2024-09-21,True
779,CUST-00780,LEAD-09099,2022-10-16,11/10/2023,12.0,45.0,-1.0,5180.47,62165.64,Pro,...,23,Critical,Not Started,Premium,22,2023-04-17,0.00,5,11/10/2023,False

In [21]:
tables = {
    'churn': churn,
    'companies': companies,
    'customers': customers,
    'deals': deals,
    'leads': leads,
    'pricing': pricing,
    'buyer' : buyer
}

for table_name, df in tables.items():
    print(f"\n {table_name.upper()} ")

    categorical_cols = df.select_dtypes(include='object').columns

    for col in categorical_cols:
        print(f"\n{col}")
        print(df[col].value_counts(dropna=False).head(30))

 CHURN

churn_id
churn_id
CHRN-00001    1
CHRN-00002    1
CHRN-00003    1
CHRN-00004    1
CHRN-00005    1
CHRN-00006    1
CHRN-00007    1
CHRN-00008    1
CHRN-00009    1
CHRN-00010    1
CHRN-00011    1
CHRN-00012    1
CHRN-00013    1
CHRN-00014    1
CHRN-00015    1
CHRN-00016    1
CHRN-00017    1
CHRN-00018    1
CHRN-00019    1
CHRN-00020    1
CHRN-00021    1
CHRN-00022    1
CHRN-00023    1
CHRN-00024    1
CHRN-00025    1
CHRN-00026    1
CHRN-00027    1
CHRN-00028    1
CHRN-00029    1
CHRN-00030    1
Name: count, dtype: int64

customer_id
customer_id
CUST-00006    1
CUST-00010    1
CUST-00013    1
CUST-00020    1
CUST-00027    1
CUST-00030    1
CUST-00032    1
CUST-00037    1
CUST-00046    1
CUST-00050    1
CUST-00053    1
CUST-00056    1
CUST-00057    1
CUST-00059    1
CUST-00062    1
CUST-00078    1
CUST-00080    1
CUST-00081    1
CUST-00083    1
CUST-00086    1
CUST-00089    1
CUST-00090    1
CUST-00092    1
CUST-00095    1
CUST-00104    1
CUST-00106    1
CUST-00109    1
CUST-00112    1
CUST-00119    1
CUST-00122    1
Name: count, dtype: int64

churn_date
churn_date
2025-01-06          2
2023-09-17          2
2023-10-07          2
12 Jun 2024         2
2024-04-25          2
2025-03-30          2
2024-12-27          2
2024-12-14          2
Aug 19, 2024        1
2024-04-27          1
03 May 2024         1
2023-07-10          1
15/07/2023          1
Nov 13, 2024        1
2023/04/26          1
2024-12-18          1
April 28, 2024      1
January 17, 2025    1
28-01-2024          1
2024-08-30          1
May 26, 2023        1
01/24/2024          1
2024-06-23          1
2025-03-28          1
14 Jul 2024         1
07/26/2023          1
23/05/2024          1
2023-12-11          1
2024-10-13          1
2024/05/26          1
Name: count, dtype: int64

churn_reason
churn_reason
Poor support              48
Business closed           42
Downgraded                37
Switched to competitor    30
Price                     26
Missing features          24
Name: count, dtype: int64

churn_type
churn_type
Voluntary      156
Involuntary     51
Name: count, dtype: int64

 COMPANIES

company_id
company_id
COMP-08811    1
COMP-00001    1
COMP-00002    1
COMP-00003    1
COMP-00004    1
COMP-00005    1
COMP-00006    1
COMP-00007    1
COMP-00008    1
COMP-00009    1
COMP-00010    1
COMP-08795    1
COMP-08794    1
COMP-08793    1
COMP-08792    1
COMP-08791    1
COMP-08790    1
COMP-08789    1
COMP-08788    1
COMP-08787    1
COMP-08786    1
COMP-08785    1
COMP-08784    1
COMP-08783    1
COMP-08782    1
COMP-08781    1
COMP-08780    1
COMP-00043    1
COMP-00042    1
COMP-00041    1
Name: count, dtype: int64

company_name
company_name
Lopez-Haley                          1
Montgomery, Green and Conrad         1
Nguyen, Mitchell and West            1
Vazquez Ltd                          1
Cameron Group                        1
Smith-Phillips                       1
Owens, Willis and Mcdonald           1
Pearson-Williams                     1
Greer, Matthews and Melendez         1
Barron-Cole                          1
Rivas PLC                            1
Perez-Smith                          1
Skinner-Patel                        1
Brown, Koch and Austin               1
Guerrero, Hall and Sampson           1
Brewer-Baxter                        1
Mcfarland, Alexander and Morrison    1
Berry, Bonilla and Myers             1
Mccullough-Petersen                  1
Hernandez, Flores and Larson         1
Austin, Gordon and Moore             1
Cabrera LLC                          1
Estrada LLC                          1
Pearson LLC                          1
Lyons-Graves                         1
Mcguire-Rodriguez                    1
Padilla, Ochoa and Schmidt           1
Nguyen, Harris and Kemp              1
Hamilton, Oneal and Vaughan          1
Robinson Inc                         1
Name: count, dtype: int64

website
website
www.cartergroup.com        3
www.hollandandsons.com     3
www.rodriguezandson.com    3
www.leeinc.com             3
www.williamsmoorean.com    3
www.johnsonllc.com         3
www.garcialtd.com          3
www.chavezjohnsonan.com    3
www.lanellc.com            2
www.duncanltd.com          2
www.changinc.com           2
www.ramirezplc.com         2
www.hamiltonsmithan.com    2
www.taylorllc.com          2
www.petersoninc.com        2
www.scottandsons.com       2
www.floresplc.com          2
www.stewartsalinasa.com    2
www.holtllc.com            2
www.leeltd.com             2
www.johnsonwilliams.com    2
www.johnsonrobinson.com    2
www.jonesgallaghera.com    2
www.clarkinc.com           2
www.delgadollc.com         2
www.bennettinc.com         2
www.garciagutierrez.com    2
www.castroltd.com          2
www.drakeltd.com           2
www.hernandezpereza.com    2
Name: count, dtype: int64

linkedin_url
linkedin_url
linkedin.com/company/carter-inc              2
linkedin.com/company/hernandez-perez-and-    2
linkedin.com/company/johnson-jackson-and-    2
linkedin.com/company/campbell-plc            2
linkedin.com/company/garcia-williams-and-    2
linkedin.com/company/phillips-llc            2
linkedin.com/company/duncan-ltd              2
linkedin.com/company/hicks-group             2
linkedin.com/company/lopez-llc               2
linkedin.com/company/johnson-ramirez-and-    2
linkedin.com/company/brown-ltd               2
linkedin.com/company/moran-and-sons          2
linkedin.com/company/sanders-group           2
linkedin.com/company/williams-martinez-an    2
linkedin.com/company/smith-inc               2
linkedin.com/company/mason-llc               2
linkedin.com/company/payne-williams-and-h    2
linkedin.com/company/robinson-plc            2
linkedin.com/company/johnson-group           2
linkedin.com/company/roberts-rodriguez       2
linkedin.com/company/williams-johnson-and    2
linkedin.com/company/garcia-gutierrez-and    2
linkedin.com/company/johnson-williams-and    2
linkedin.com/company/rodriguez-plc           2
linkedin.com/company/mueller-white-and-ca    2
linkedin.com/company/lee-inc                 2
linkedin.com/company/johnson-inc             2
linkedin.com/company/williams-campbell-an    2
linkedin.com/company/clark-inc               2
linkedin.com/company/garcia-ltd              2
Name: count, dtype: int64

industry
industry
CyberSecurity     764
EdTech            749
LogisTech         749
HealthTech        732
LegalTech         714
MarTech           686
HR Tech           685
FinTech           684
NaN               267
cyber-security    110
HEALTHTECH        100
LOGISTECH          98
EDTECH             96
Health-Tech        94
logistech          94
Cyber Security     93
Health Tech        90
cybersecurity      90
Legal-Tech         90
MARTECH            87
Logis Tech         87
Ed Tech            84
LEGALTECH          84
Fin Tech           83
CYBERSECURITY      83
hr tech            81
Mar Tech           81
fintech            80
ed-tech            80
HRTech             79
Name: count, dtype: int64

company_type
company_type
Government    1835
Private       1780
Public        1778
Non-Profit    1750
Startup       1668
Name: count, dtype: int64

company_size
company_size
11-50               1003
201-500              996
1000+                984
501-1000             978
51-200               966
1-10                 961
NaN                  438
Mid-Market           163
201–500              147
501 to 1000          135
201 to 500           127
501–1000             122
Small                122
Large                120
Mid-size             112
51–200               109
Small (11-50)        109
Medium               104
11–50                103
Solo/Micro            97
1,000+                94
51 to 200             92
1 to 10               92
1–10                  91
11 to 50              85
Enterprise            85
< 10                  83
Micro                 82
Large Enterprise      80
1000 +                66
Name: count, dtype: int64

region
region
Europe                  1351
LATAM                   1339
MEA                     1336
North America           1335
APAC                    1327
apac                     126
LatAm                    125
Latin America            114
latam                    112
EUROPE                   112
AP                       109
Asia-Pacific             109
mea                      109
EU                       108
europe                   106
LAT AM                    99
N. America                98
EUR                       97
north america             96
Middle East & Africa      96
M.E.A.                    93
Asia Pacific              92
NaN                       84
Middle East               84
NORTH AMERICA             80
N America                 74
Name: count, dtype: int64

country
country
United States     692
Canada            589
Mexico            486
Colombia          431
Brazil            429
Argentina         418
Australia         393
Singapore         367
UAE               356
Japan             355
Germany           337
South Africa      333
United Kingdom    333
France            320
Nigeria           314
Peru              269
Chile             242
Egypt             241
Kenya             239
Saudi Arabia      235
India             228
South Korea       227
Spain             209
Italy             202
Sweden            199
New Zealand       193
Netherlands       174
Name: count, dtype: int64

primary_contact_title
primary_contact_title
Chief Revenue Officer    726
Founder                  698
Head of Growth           696
Co-Founder               694
Sales Director           687
Director of Revenue      686
CTO                      680
CFO                      677
VP of Marketing          672
Head of Operations       667
VP of Sales              667
COO                      641
CEO                      620
Name: count, dtype: int64

tech_stack
tech_stack
Salesforce                137
GCP                       132
Zoom                      132
Snowflake                 128
Pipedrive                 125
Twilio                    122
Zendesk                   118
Stripe                    118
Intercom                  118
AWS                       117
Databricks                117
Asana                     115
Monday.com                112
HubSpot                   111
Azure                     111
Notion                    110
Jira                      106
Slack                     106
Marketo                    91
Salesforce; Pipedrive      16
Azure; Jira                13
Intercom; Azure            13
Notion; Twilio             13
Pipedrive; Intercom        13
Slack; Marketo             12
Asana; Marketo             12
Notion; Pipedrive          12
Databricks; Salesforce     11
AWS; Snowflake             11
Databricks; Zoom           11
Name: count, dtype: int64

lifecycle_stage
lifecycle_stage
Opportunity    1310
Evangelist     1295
MQL            1293
Lead           1280
Customer       1237
Other          1226
SQL            1170
Name: count, dtype: int64

lead_status
lead_status
New                     1294
Attempted to Contact    1279
In Progress             1270
Open                    1260
Connected               1247
Unqualified             1243
Bad Timing              1218
Name: count, dtype: int64

date_added
date_added
2025-10-16    15
2023-01-19    14
2025-03-08    14
2026-06-14    14
2025-01-13    14
2025-02-02    14
2025-03-01    13
2024-05-06    13
2025-03-12    13
2022-07-31    13
2025-07-16    13
2024-01-10    13
2026-06-10    13
2024-03-11    13
2026-06-11    13
2024-04-06    12
2023-10-19    12
2022-10-28    12
2025-10-18    12
2024-11-24    12
2025-04-17    12
2025-08-07    12
2022-08-16    12
2026-01-11    12
2023-10-29    12
2024-01-05    12
2025-06-12    11
2025-06-06    11
2024-03-22    11
2025-04-29    11
Name: count, dtype: int64

last_activity_date
last_activity_date
2026-06-22    53
2026-06-21    46
2026-06-23    46
2026-06-15    44
2026-06-16    44
2026-06-08    39
2026-06-14    38
2026-06-19    37
2026-06-17    35
2026-06-11    34
2026-06-12    34
2026-06-20    34
2026-05-13    32
2026-05-28    32
2026-06-18    31
2026-05-08    29
2026-06-13    29
2026-04-16    29
2026-05-24    29
2026-04-27    28
2026-06-09    27
2026-06-05    27
2026-05-10    27
2026-06-02    27
2026-05-23    27
2026-05-29    27
2026-05-09    26
2026-05-25    26
2026-05-19    25
2026-05-31    25
Name: count, dtype: int64

notes
notes
NaN                                                                  5828
Save thought write effort step.                                         1
Control special course us ask few study important simply.               1
Together per affect establish rather pay truth any.                     1
Return thank government past call.                                      1
Item about wind score me be.                                            1
One street class each bad.                                              1
Drop employee democratic father lay clear woman.                        1
Enough property well community.                                         1
Opportunity myself us whether majority must nice.                       1
Hope end brother deal act high.                                         1
Mother theory will discover sort agent degree show.                     1
Concern form himself dinner quickly become within.                      1
Education address buy wide show center southern.                        1
Night a until have.                                                     1
These local during worker new.                                          1
Where day beyond however best our his bad close toward everybody.       1
Population former everything act us shoulder test.                      1
Project trouble after personal.                                         1
Vote really president attack see view.                                  1
Information leg skill never seek science community door.                1
Particularly wind world process executive.                              1
Three real building who.                                                1
Sound production these imagine small worry.                             1
Generation occur green or wait.                                         1
However most already offer any movement.                                1
Wife far generation itself spend start offer front.                     1
Century visit great person.                                             1
Fine trial second cost professor.                                       1
Production determine return them building financial treat.              1
Name: count, dtype: int64

 CUSTOMERS

customer_id
customer_id
CUST-00871    1
CUST-00001    1
CUST-00002    1
CUST-00003    1
CUST-00004    1
CUST-00005    1
CUST-00006    1
CUST-00855    1
CUST-00854    1
CUST-00853    1
CUST-00852    1
CUST-00851    1
CUST-00850    1
CUST-00849    1
CUST-00848    1
CUST-00847    1
CUST-00846    1
CUST-00845    1
CUST-00844    1
CUST-00843    1
CUST-00842    1
CUST-00841    1
CUST-00840    1
CUST-00039    1
CUST-00038    1
CUST-00037    1
CUST-00036    1
CUST-00035    1
CUST-00034    1
CUST-00033    1
Name: count, dtype: int64

lead_id
lead_id
LEAD-01185    1
LEAD-05315    1
LEAD-09226    1
LEAD-00108    1
LEAD-08803    1
LEAD-01108    1
LEAD-04123    1
LEAD-00877    1
LEAD-07080    1
LEAD-00513    1
LEAD-03344    1
LEAD-03148    1
LEAD-06618    1
LEAD-07422    1
LEAD-02850    1
LEAD-02490    1
LEAD-02428    1
LEAD-04001    1
LEAD-04381    1
LEAD-00826    1
LEAD-00729    1
LEAD-07165    1
LEAD-07358    1
LEAD-06649    1
LEAD-07755    1
LEAD-09868    1
LEAD-03539    1
LEAD-03182    1
LEAD-08894    1
LEAD-00953    1
Name: count, dtype: int64

contract_start_date
contract_start_date
2022-08-07           3
2024-05-07           3
2024-06-26           3
2022-11-23           3
2024-05-12           3
2022-09-09           3
2024-08-25           3
December 31, 2023    3
2023-07-17           2
2022-07-30           2
2023-03-24           2
2022-03-22           2
2023-12-23           2
2022-10-02           2
2022-07-18           2
08/26/2022           2
2023-09-01           2
2022-06-15           2
2024-09-18           2
2023-02-11           2
2024-02-03           2
2024-05-29           2
2024-08-02           2
2024-06-28           2
Apr 30, 2024         2
2024-05-16           2
2023-12-27           2
2022-12-28           2
2024-03-19           2
2024-05-09           2
Name: count, dtype: int64

contract_end_date
contract_end_date
2026-04-14    3
2025-05-04    3
2025-04-25    3
2026-06-14    3
2027-04-27    3
2026-05-19    3
2026-09-18    3
2026-05-02    3
2025-07-26    3
2026-09-24    3
2025-03-02    3
2025-11-01    3
2025-10-25    3
2026-04-11    2
2026-12-22    2
2024-11-06    2
2026-08-09    2
2025-12-30    2
2026-04-24    2
2023-09-27    2
2024-02-28    2
07/02/2026    2
2024-03-20    2
2026-06-18    2
2025-02-13    2
2026-12-29    2
2025-06-11    2
2026-12-07    2
2025-12-20    2
2027-02-14    2
Name: count, dtype: int64

plan_tier
plan_tier
Starter       232
Enterprise    219
Growth        190
Pro           185
NaN            45
Name: count, dtype: int64

customer_success_rep
customer_success_rep
Anna Duncan        170
Nancy Torres       159
Lauren Martinez    141
Mikayla Farley     136
Erin Lang          133
Joshua Phillips    132
Name: count, dtype: int64

health_status
health_status
Critical    466
At Risk     385
Healthy      20
Name: count, dtype: int64

onboarding_status
onboarding_status
Complete       583
In Progress    151
Not Started    137
Name: count, dtype: int64

support_tier
support_tier
Standard      467
Enterprise    219
Premium       185
Name: count, dtype: int64

last_login_date
last_login_date
2025-08-23    5
2026-04-23    4
2024-07-06    4
2024-12-30    4
2025-02-11    4
2024-08-01    4
2025-10-21    4
2026-06-18    4
2024-08-30    4
2026-05-05    4
2026-05-12    4
2025-12-24    4
2026-02-22    4
2025-01-11    3
2026-04-22    3
2024-05-22    3
2025-02-12    3
2025-01-29    3
2023-12-25    3
2026-06-23    3
2025-08-17    3
2025-03-20    3
2026-04-18    3
2025-06-28    3
2025-02-06    3
2026-05-07    3
2024-04-30    3
2025-03-30    3
2024-12-29    3
2025-12-13    3
Name: count, dtype: int64

renewal_date
renewal_date
2026-04-14    3
2025-05-04    3
2025-04-25    3
2026-06-14    3
2027-04-27    3
2026-05-19    3
2026-09-18    3
2026-05-02    3
2025-07-26    3
2026-09-24    3
2025-03-02    3
2025-11-01    3
2025-10-25    3
2026-04-11    2
2026-12-22    2
2024-11-06    2
2026-08-09    2
2025-12-30    2
2026-04-24    2
2023-09-27    2
2024-02-28    2
07/02/2026    2
2024-03-20    2
2026-06-18    2
2025-02-13    2
2026-12-29    2
2025-06-11    2
2026-12-07    2
2025-12-20    2
2027-02-14    2
Name: count, dtype: int64

 DEALS

deal_id
deal_id
DEAL-01659    1
DEAL-00001    1
DEAL-00002    1
DEAL-00003    1
DEAL-00004    1
DEAL-00005    1
DEAL-00006    1
DEAL-00007    1
DEAL-00008    1
DEAL-00009    1
DEAL-00010    1
DEAL-01643    1
DEAL-01642    1
DEAL-01641    1
DEAL-01640    1
DEAL-01639    1
DEAL-01638    1
DEAL-01637    1
DEAL-01636    1
DEAL-01635    1
DEAL-01634    1
DEAL-01633    1
DEAL-01632    1
DEAL-01631    1
DEAL-01630    1
DEAL-01629    1
DEAL-01628    1
DEAL-00043    1
DEAL-00042    1
DEAL-00041    1
Name: count, dtype: int64

lead_id
lead_id
LEAD-01185    1
LEAD-05315    1
LEAD-01958    1
LEAD-09226    1
LEAD-00108    1
LEAD-08803    1
LEAD-09791    1
LEAD-08300    1
LEAD-06111    1
LEAD-01108    1
LEAD-04123    1
LEAD-08111    1
LEAD-05117    1
LEAD-03243    1
LEAD-09722    1
LEAD-01307    1
LEAD-05531    1
LEAD-07995    1
LEAD-03305    1
LEAD-04738    1
LEAD-08165    1
LEAD-05856    1
LEAD-02912    1
LEAD-01844    1
LEAD-02386    1
LEAD-00263    1
LEAD-04549    1
LEAD-08491    1
LEAD-05655    1
LEAD-01670    1
Name: count, dtype: int64

plan_tier
plan_tier
Starter         321
Enterprise      320
Pro             295
Growth          276
Start            36
Professional     35
Grow             35
GROWTH           28
professional     28
PRO              27
ENTERPRISE       27
basic            27

In [22]:
tables = {
    'churn': churn,
    'companies': companies,
    'customers': customers,
    'deals': deals,
    'leads': leads,
    'pricing': pricing,
    'buyer' : buyer
}

for table_name, df in tables.items():
    print(f"{table_name.upper()}")

    print(df.describe(include='all'))

CHURN
          churn_id customer_id churned  churn_date  churn_reason  \
count          207         207     207         207           207
unique         207         207       1         199             6
top     CHRN-00001  CUST-00006    True  2025-01-06  Poor support
freq             1           1     207           2            48
mean           NaN         NaN     NaN         NaN           NaN
std            NaN         NaN     NaN         NaN           NaN
min            NaN         NaN     NaN         NaN           NaN
25%            NaN         NaN     NaN         NaN           NaN
50%            NaN         NaN     NaN         NaN           NaN
75%            NaN         NaN     NaN         NaN           NaN
max            NaN         NaN     NaN         NaN           NaN

        days_to_churn churn_type refund_issued  refund_amount_usd  \
count      207.000000        207           207         207.000000
unique            NaN          2             2                NaN
top               NaN  Voluntary         False                NaN
freq              NaN        156           151                NaN
mean       224.057971        NaN           NaN         852.477246
std        198.738196        NaN           NaN        2442.901795
min       -167.000000        NaN           NaN           0.000000
25%         71.000000        NaN           NaN           0.000000
50%        171.000000        NaN           NaN           0.000000
75%        325.000000        NaN           NaN         308.900000
max        924.000000        NaN           NaN       18738.390000

       exit_survey_completed win_back_attempted win_back_successful  \
count                    207                207                 207
unique                     2                  2                   2
top                     True              False               False
freq                     132                128                 193
mean                     NaN                NaN                 NaN
std                      NaN                NaN                 NaN
min                      NaN                NaN                 NaN
25%                      NaN                NaN                 NaN
50%                      NaN                NaN                 NaN
75%                      NaN                NaN                 NaN
max                      NaN                NaN                 NaN

        final_mrr_usd  churned_arr_usd
count      207.000000       207.000000
unique            NaN              NaN
top               NaN              NaN
freq              NaN              NaN
mean      3663.678019     43964.136232
std       4668.373101     56020.477211
min         46.620000       559.440000
25%        623.350000      7480.200000
50%       1532.070000     18384.840000
75%       4978.285000     59739.420000
max      21326.570000    255918.840000
COMPANIES
        company_id company_name              website  \
count         8811         8811                 8811
unique        8811         8811                 8583
top     COMP-08811  Lopez-Haley  www.cartergroup.com
freq             1            1                    3
mean           NaN          NaN                  NaN
std            NaN          NaN                  NaN
min            NaN          NaN                  NaN
25%            NaN          NaN                  NaN
50%            NaN          NaN                  NaN
75%            NaN          NaN                  NaN
max            NaN          NaN                  NaN

                           linkedin_url       industry company_type  \
count                              8811           8544         8811
unique                             8748             42            5
top     linkedin.com/company/carter-inc  CyberSecurity   Government
freq                                  2            764         1835
mean                                NaN            NaN          NaN
std                                 NaN            NaN          NaN
min                                 NaN            NaN          NaN
25%                                 NaN            NaN          NaN
50%                                 NaN            NaN          NaN
75%                                 NaN            NaN          NaN
max                                 NaN            NaN          NaN

       company_size  number_of_employees  annual_revenue_usd  region  \
count          8373          8811.000000        8.373000e+03    8727
unique           30                  NaN                 NaN      25
top           11-50                  NaN                 NaN  Europe
freq           1003                  NaN                 NaN    1351
mean            NaN          3567.218477        5.045846e+08     NaN
std             NaN         10031.949209        1.112713e+09     NaN
min             NaN             1.000000        5.200000e+04     NaN
25%             NaN            12.500000        2.545000e+06     NaN
50%             NaN           116.000000        1.982800e+07     NaN
75%             NaN           412.000000        2.895940e+08     NaN
max             NaN         49965.000000        4.999357e+09     NaN

              country  primary_contact_title  tech_stack lifecycle_stage  \
count            8811                   8811        8811            8811
unique             27                     13        4398               7
top     United States  Chief Revenue Officer  Salesforce     Opportunity
freq              692                    726         137            1310
mean              NaN                    NaN         NaN             NaN
std               NaN                    NaN         NaN             NaN
min               NaN                    NaN         NaN             NaN
25%               NaN                    NaN         NaN             NaN
50%               NaN                    NaN         NaN             NaN
75%               NaN                    NaN         NaN             NaN
max               NaN                    NaN         NaN             NaN

       lead_status  date_added last_activity_date  \
count         8811        8811               8811
unique           7        1460               1256
top            New  2025-10-16         2026-06-22
freq          1294          15                 53
mean           NaN         NaN                NaN
std            NaN         NaN                NaN
min            NaN         NaN                NaN
25%            NaN         NaN                NaN
50%            NaN         NaN                NaN
75%            NaN         NaN                NaN
max            NaN         NaN                NaN

                                           notes
count                                       2983
unique                                      2983
top     Film kitchen show system avoid actually.
freq                                           1
mean                                         NaN
std                                          NaN
min                                          NaN
25%                                          NaN
50%                                          NaN
75%                                          NaN
max                                          NaN
CUSTOMERS
       customer_id     lead_id contract_start_date contract_end_date  \
count          871         871                 871               871
unique         871         871                 773               781
top     CUST-00871  LEAD-01185          2022-08-07        2026-04-14
freq             1           1                   3                 3
mean           NaN         NaN                 NaN               NaN
std            NaN         NaN                 NaN               NaN
min            NaN         NaN                 NaN               NaN
25%            NaN         NaN                 NaN               NaN
50%            NaN         NaN                 NaN               NaN
75%            NaN         NaN                 NaN               NaN
max            NaN         NaN                 NaN               NaN

        contract_length_months  product_usage_score   nps_score       mrr_usd  \
count               871.000000           871.000000  871.000000    871.000000
unique                     NaN                  NaN         NaN           NaN
top                        NaN                  NaN         NaN           NaN
freq                       NaN                  NaN         NaN           NaN
mean                 24.179104            56.163031    5.136625   4203.531975
std                   9.719991            29.224711    3.281565   5005.110581
min                  12.000000            -5.000000   -1.000000     46.620000
25%                  12.000000            32.000000    2.000000    752.205000
50%                  24.000000            55.000000    5.000000   2104.990000
75%                  36.000000            80.000000    8.000000   5678.185000
max                  36.000000           200.000000   15.000000  21843.680000

              arr_usd plan_tier  ... health_score  health_status  \
count      871.000000       826  ...   871.000000            871
unique            NaN         4  ...          NaN              3
top               NaN   Starter  ...          NaN       Critical
freq              NaN       232  ...          NaN            466
mean     50442.383697       NaN  ...    37.933410            NaN
std      60061.326976       NaN  ...    15.475458            NaN
min        559.440000       NaN  ...     7.000000            NaN
25%       9026.460000       NaN  ...    25.500000            NaN
50%      25259.880000       NaN  ...    37.000000            NaN
75%      68138.220000       NaN  ...    49.000000            NaN
max     262124.160000       NaN  ...   118.000000            NaN

       onboarding_status support_tier number_of_support_tickets  \
count                871          871                871.000000
unique                 3            3                       NaN
top             Complete     Standard                       NaN
freq                 583          467                       NaN
mean                 NaN          NaN                 12.251435
std                  NaN          NaN                  7.400212
min                  NaN          NaN                  0.000000
25%                  NaN          NaN                  6.000000
50%                  NaN          NaN                 13.000000
75%                  NaN          NaN                 19.000000
max                  NaN          NaN                 25.000000

        last_login_date expansion_revenue_usd  referrals_made  renewal_date  \
count               871            871.000000      871.000000           871
unique              609                   NaN             NaN           781
top          2025-08-23                   NaN             NaN    2026-04-14
freq                  5                   NaN             NaN             3
mean                NaN           1210.946475        2.462687           NaN
std                 NaN           2485.363872        1.672130           NaN
min                 NaN              0.000000        0.000000           NaN
25%                 NaN              0.000000        1.000000           NaN
50%                 NaN              0.000000        2.000000           NaN
75%                 NaN            611.650000        4.000000           NaN
max                 NaN           9943.840000        5.000000           NaN

       auto_renew
count         871
unique          2
top          True
freq          600
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

[11 rows x 21 columns]
DEALS
           deal_id     lead_id plan_tier   plan_id  deal_value_annual_usd  \
count         1659        1659      1659      1659           1.610000e+03
unique        1659        1659        22         4                    NaN
top     DEAL-01659  LEAD-01185   Starter  PLAN-001                    NaN
freq             1           1       321       448                    NaN
mean           NaN         NaN       NaN       NaN           3.736376e+05
std            NaN         NaN       NaN       NaN           6.463758e+05
min            NaN         NaN       NaN       NaN          -1.480171e+06
25%            NaN         NaN       NaN       NaN           1.850433e+04
50%            NaN         NaN       NaN       NaN           6.558318e+04
75%            NaN         NaN       NaN       NaN           2.519176e+05
max            NaN         NaN       NaN       NaN           5.686737e+06

        close_date           loss_reason  deal_stage  deal_probability_pct  \
count         1659                   833        1659           1659.000000
unique        1289                     6           5                   NaN
top     2024-10-04  Went with competitor  Closed Won                   NaN
freq             5                   152         454                   NaN
mean           NaN                   NaN         NaN             65.514768
std            NaN                   NaN         NaN             37.653733
min            NaN                   NaN         NaN              0.000000
25%            NaN                   NaN         NaN             53.000000
50%            NaN                   NaN         NaN             80.000000
75%            NaN                   NaN         NaN            100.000000
max            NaN                   NaN         NaN            100.000000

           deal_type deal_currency expected_close_date  weighted_value_usd  \
count           1659          1659                1659        1.659000e+03
unique             4             5                 871                 NaN
top     New Business           USD          2024-02-03                 NaN
freq             851           912                   8                 NaN
mean             NaN           NaN                 NaN        2.394866e+05
std              NaN           NaN                 NaN        5.204497e+05
min              NaN           NaN                 NaN       -1.480171e+06
25%              NaN           NaN                 NaN        0.000000e+00
50%              NaN           NaN                 NaN        2.190082e+04
75%              NaN           NaN                 NaN        1.232356e+05
max              NaN           NaN                 NaN        5.686737e+06

        number_of_contacts  competitor  discount_pct contract_type  \
count          1659.000000        1244   1659.000000          1659
unique                 NaN           6           NaN             3
top                    NaN  Monday.com           NaN        Annual
freq                   NaN         230           NaN           568
mean              5.600964         NaN      5.106088           NaN
std               2.858319         NaN      7.779440           NaN
min               1.000000         NaN      0.000000           NaN
25%               3.000000         NaN      0.000000           NaN
50%               6.000000         NaN      0.000000           NaN
75%               8.000000         NaN      9.900000           NaN
max              10.000000         NaN     25.000000           NaN

           next_step
count           1296
unique             7
top     Legal review
freq             200
mean             NaN
std              NaN
min              NaN
25%              NaN
50%              NaN
75%              NaN
max              NaN
LEADS
           lead_id  company_id     contact_name  \
count        10000       10000            10000
unique       10000        8785             9496
top     LEAD-06421  COMP-01241  Brandon Johnson
freq             1          16                5
mean           NaN         NaN              NaN
std            NaN         NaN              NaN
min            NaN         NaN              NaN
25%            NaN         NaN              NaN
50%            NaN         NaN              NaN
75%            NaN         NaN              NaN
max            NaN         NaN              NaN

                              contact_email created_date  lead_source  \
count                                 10000        10000        10000
unique                                10000         4021           40
top     kylefitzpatrick@carpenter-green.com   2024-10-12  Paid Search
freq                                      1           13          942
mean                                    NaN          NaN          NaN
std                                     NaN          NaN          NaN
min                                     NaN          NaN          NaN
25%                                     NaN          NaN          NaN
50%                                     NaN          NaN          NaN
75%                                     NaN          NaN          NaN
max                                     NaN          NaN          NaN

           assigned_rep funnel_stage  days_lead_to_mql  days_mql_to_sql  ...  \
count              9600        10000       5106.000000      2948.000000  ...
unique               47           27               NaN              NaN  ...
top     Anthony Clayton         Lead               NaN              NaN  ...
freq                773         3692               NaN              NaN  ...
mean                NaN          NaN          7.502350        12.060380  ...
std                 NaN          NaN          4.010331         5.589001  ...
min                 NaN          NaN          1.000000         3.000000  ...
25%                 NaN          NaN          4.000000         7.000000  ...
50%                 NaN          NaN          7.000000        12.000000  ...
75%                 NaN          NaN         11.000000        17.000000  ...
max                 NaN          NaN         14.000000        21.000000  ...

        number_of_contacts  last_contact_method         sdr_owner utm_source  \
count         10000.000000                 8674             10000       8760
unique                 NaN                    4                 8          7
top                    NaN                Email  Elizabeth Jordan     direct
freq                   NaN                 3733              1277       1304
mean              7.523400                  NaN               NaN        NaN
std               4.632148                  NaN               NaN        NaN
min               0.000000                  NaN               NaN        NaN
25%               4.000000                  NaN               NaN        NaN
50%               8.000000                  NaN               NaN        NaN
75%              12.000000                  NaN               NaN        NaN
max              15.000000                  NaN               NaN        NaN

       utm_medium  utm_campaign email_opt_in   phone_number  \
count        8599          8611        10000           7460
unique          6             6            2           7460
top           cpc   q1_outbound         True  (535)948-2546
freq         1480          1456         7481              1
mean          NaN           NaN          NaN            NaN
std           NaN           NaN          NaN            NaN
min           NaN           NaN          NaN            NaN
25%           NaN           NaN          NaN            NaN
50%           NaN           NaN          NaN            NaN
75%           NaN           NaN          NaN            NaN
max           NaN           NaN          NaN            NaN

                             job_title  \
count                            10000
unique                             639
top     Armed forces technical officer
freq                                28
mean                               NaN
std                                NaN
min                                NaN
25%                                NaN
50%                                NaN
75%                                NaN
max                                NaN


In [23]:
company_size = {
    '1 to 10': '1-10',
    '1–10': '1-10',
    '< 10': '1-10',
    'Solo/Micro': '1-10',
    'Micro': '1-10',

    '11 to 50': '11-50',
    '11–50': '11-50',
    'Small (11-50)': '11-50',

    '51 to 200': '51-200',
    '51–200': '51-200',
    'Small': '51-200',
    'Mid-size': '51-200',

    '201–500': '201-500',
    '201 to 500': '201-500',
    'Medium': '201-500',
    'Mid-Market': '201-500',

    '501–1000': '501-1000',
    '501 to 1000': '501-1000',
    'Large': '501-1000',

    '1,000+': '1000+',
    '1000 +': '1000+',
    'Enterprise': '1000+',
    'Large Enterprise': '1000+',
    '>1000': '1000+'
}

companies['company_size'] = companies['company_size'].replace(company_size)

In [24]:
companies['company_size'].value_counts(dropna=False)

company_size
201-500     1537
1-10        1406
51-200      1401
1000+       1374
501-1000    1355
11-50       1300
NaN          438
Name: count, dtype: int64

In [25]:
industry = {

    'cybersecurity': 'CyberSecurity',
    'cyber-security': 'CyberSecurity',
    'cyber security': 'CyberSecurity',
    'CYBERSECURITY': 'CyberSecurity',
    'Cyber Security': 'CyberSecurity',

    'healthtech': 'HealthTech',
    'health-tech': 'HealthTech',
    'health tech': 'HealthTech',
    'HEALTHTECH': 'HealthTech',
    'Health-Tech': 'HealthTech',
    'Health Tech': 'HealthTech',

    'fintech': 'FinTech',
    'fin tech': 'FinTech',
    'fin-tech': 'FinTech',
    'FINTECH': 'FinTech',
    'Fin Tech': 'FinTech',
    'Fintech': 'FinTech',

    'hr tech': 'HR Tech',
    'hrtech': 'HR Tech',
    'hr-tech': 'HR Tech',
    'h.r. tech': 'HR Tech',
    'HRTech': 'HR Tech',
    'HR-Tech': 'HR Tech',
    'H.R. Tech': 'HR Tech',

    'logistech': 'LogisTech',
    'logis tech': 'LogisTech',
    'logistics tech': 'LogisTech',
    'LOGISTECH': 'LogisTech',
    'Logis Tech': 'LogisTech',
    'Logistics Tech': 'LogisTech',

    'martech': 'MarTech',
    'mar tech': 'MarTech',
    'mar-tech': 'MarTech',
    'MARTECH': 'MarTech',
    'Mar Tech': 'MarTech',

    'legaltech': 'LegalTech',
    'legal tech': 'LegalTech',
    'legal-tech': 'LegalTech',
    'LEGALTECH': 'LegalTech',
    'Legal Tech': 'LegalTech',
    'Legal-Tech': 'LegalTech',

    'edtech': 'EdTech',
    'ed tech': 'EdTech',
    'ed-tech': 'EdTech',
    'EDTECH': 'EdTech',
    'Ed Tech': 'EdTech'
}

companies['industry'] = companies['industry'].replace(industry)

In [26]:
companies['industry'].value_counts(dropna=False)

industry
CyberSecurity    1140
LogisTech        1105
HealthTech       1088
EdTech           1085
HR Tech          1058
FinTech          1051
LegalTech        1018
MarTech           999
NaN               267
Name: count, dtype: int64

In [27]:
region = {
    'N America':'North America',
    'NORTH AMERICA' : 'North America',
    'north america' : 'North America',
    'N. America' : 'North America',

    'Middle East' : 'MEA',
    'M.E.A.': 'MEA',
    'Middle East & Africa' : 'MEA',
    'mea' : 'MEA',

    'Asia Pacific' : 'APAC',
    'Asia-Pacific' : 'APAC',
    'AP' : 'APAC',
    'apac' : 'APAC',

    'EUR' : 'Europe',
    'europe' : 'Europe',
    'EU' : 'Europe',
    'EUROPE' : 'Europe',

    'LAT AM' : 'LATAM',
    'latam' : 'LATAM',
    'LatAm' : 'LATAM',
    'Latin America' : 'LATAM'

}

companies['region'] = companies['region'].replace(region)

In [28]:
companies['region'].value_counts(dropna=False)

region
LATAM            1789
Europe           1774
APAC             1763
MEA              1718
North America    1683
NaN                84
Name: count, dtype: int64

In [29]:
companies.describe()

       number_of_employees  annual_revenue_usd
count          8811.000000        8.373000e+03
mean           3567.218477        5.045846e+08
std           10031.949209        1.112713e+09
min               1.000000        5.200000e+04
25%              12.500000        2.545000e+06
50%             116.000000        1.982800e+07
75%             412.000000        2.895940e+08
max           49965.000000        4.999357e+09

In [30]:
companies['last_activity_date'] = pd.to_datetime(
    companies['last_activity_date']
)

In [31]:
companies['date_added'] = pd.to_datetime(
    companies['date_added']
)

In [32]:
buyer['next_step_date'] = pd.to_datetime(
    buyer['next_step_date']
)

In [33]:
buyer['last_confirmed_buyer_response_date'] = pd.to_datetime(
    buyer['last_confirmed_buyer_response_date']
)

In [34]:
lead_source = {


    'Paid Search': 'Paid Search',
    'paid search': 'Paid Search',
    'PPC': 'Paid Search',
    'Paid': 'Paid Search',
    'Google Ads': 'Paid Search',


    'Organic Search': 'Organic Search',
    'organic search': 'Organic Search',
    'Organic': 'Organic Search',
    'organic': 'Organic Search',
    'SEO': 'Organic Search',


    'Product Trial': 'Product Trial',
    'product trial': 'Product Trial',
    'Trial': 'Product Trial',
    'trial': 'Product Trial',
    'Free Trial': 'Product Trial',


    'Webinar': 'Webinar',
    'WEBINAR': 'Webinar',
    'webinar': 'Webinar',
    'Web Event': 'Webinar',
    'Online Event': 'Webinar',


    'Content Download': 'Content Download',
    'content download': 'Content Download',
    'Gated Content': 'Content Download',
    'Content': 'Content Download',
    'Download': 'Content Download',


    'LinkedIn Ads': 'LinkedIn Ads',
    'linkedin ads': 'LinkedIn Ads',
    'LI Ads': 'LinkedIn Ads',


    'LinkedIn': 'LinkedIn',
    'linkedin': 'LinkedIn',


    'Referral': 'Referral',
    'REFERRAL': 'Referral',
    'referral': 'Referral',
    'Ref': 'Referral',
    'Word of Mouth': 'Referral',


    'Cold Outreach': 'Cold Outreach',
    'cold outreach': 'Cold Outreach',
    'cold-outreach': 'Cold Outreach',
    'Cold Email': 'Cold Outreach',
    'Outreach': 'Cold Outreach'
}

leads['lead_source'] = leads['lead_source'].replace(lead_source)

In [35]:
leads['lead_source'].value_counts(dropna=False)

lead_source
Paid Search         1292
Organic Search      1269
Webinar             1256
Product Trial       1249
Content Download    1247
Referral            1226
Cold Outreach       1211
LinkedIn Ads        1066
LinkedIn             184
Name: count, dtype: int64

In [36]:
funnel_stage = {


    'Lead': 'Lead',
    'lead': 'Lead',
    'New': 'Lead',
    'New Lead': 'Lead',


    'MQL': 'MQL',
    'Mql': 'MQL',
    'mql': 'MQL',
    'Marketing Qualified': 'MQL',
    'marketing qualified lead': 'MQL',


    'SQL': 'SQL',
    'Sql': 'SQL',
    'sql': 'SQL',
    'Sales Qualified': 'SQL',
    'sales qualified': 'SQL',


    'Closed Won': 'Closed Won',
    'Closed - Won': 'Closed Won',
    'closed won': 'Closed Won',
    'CLOSED WON': 'Closed Won',
    'Won': 'Closed Won',
    'WON': 'Closed Won',


    'Closed Lost': 'Closed Lost',
    'Closed - Lost': 'Closed Lost',
    'closed lost': 'Closed Lost',
    'CLOSED LOST': 'Closed Lost',
    'Lost': 'Closed Lost',
    'LOST': 'Closed Lost',


    'Unqualified': 'Unqualified'
}

leads['funnel_stage'] = leads['funnel_stage'].replace(funnel_stage)

In [37]:
leads['funnel_stage'].value_counts(dropna=False)

funnel_stage
Lead           4583
MQL            2158
SQL            1207
Closed Won      871
Closed Lost     870
Unqualified     311
Name: count, dtype: int64

In [38]:
last_contact_method = {


    'LinkedIn Message': 'LinkedIn',
}

leads['last_contact_method'] = leads['last_contact_method'].replace(last_contact_method)

In [39]:
leads['last_contact_method'].value_counts(dropna=False)

last_contact_method
Email       3733
Phone       2495
LinkedIn    2446
NaN         1326
Name: count, dtype: int64

In [40]:
utm_source = {


    'twitter': 'x',
}

leads['utm_source'] = leads['utm_source'].replace(utm_source)

In [41]:
leads['utm_source'].value_counts(dropna=False)

utm_source
direct      1304
linkedin    1292
facebook    1245
x           1242
NaN         1240
partner     1239
google      1231
email       1207
Name: count, dtype: int64

In [42]:
leads['created_date'] = pd.to_datetime(
    leads['created_date'],
    format='mixed',
    errors='coerce'
)

In [43]:
leads['last_contacted_date'] = pd.to_datetime(
    leads['last_contacted_date']
)

In [44]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10179
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   lead_id                    10000 non-null  object
 1   company_id                 10000 non-null  object
 2   contact_name               10000 non-null  object
 3   contact_email              10000 non-null  object
 4   created_date               10000 non-null  datetime64[ns]
 5   lead_source                10000 non-null  object
 6   assigned_rep               9600 non-null   object
 7   funnel_stage               10000 non-null  object
 8   days_lead_to_mql           5106 non-null   float64
 9   days_mql_to_sql            2948 non-null   float64
 10  days_sql_to_opportunity    1741 non-null   float64
 11  days_opportunity_to_close  1741 non-null   float64
 12  lead_score                 10000 non-null  int64
 13  lead_status                10000 non-null  object
 14  last_contacted_date        10000 non-null  datetime64[ns]
 15  number_of_contacts         10000 non-null  int64
 16  last_contact_method        8674 non-null   object
 17  sdr_owner                  10000 non-null  object
 18  utm_source                 8760 non-null   object
 19  utm_medium                 8599 non-null   object
 20  utm_campaign               8611 non-null   object
 21  email_opt_in               10000 non-null  bool
 22  phone_number               7460 non-null   object
 23  job_title                  10000 non-null  object
 24  notes                      2029 non-null   object
dtypes: bool(1), datetime64[ns](2), float64(4), int64(2), object(16)
memory usage: 1.9+ MB

In [45]:
leads.isna().sum()

lead_id                         0
company_id                      0
contact_name                    0
contact_email                   0
created_date                    0
lead_source                     0
assigned_rep                  400
funnel_stage                    0
days_lead_to_mql             4894
days_mql_to_sql              7052
days_sql_to_opportunity      8259
days_opportunity_to_close    8259
lead_score                      0
lead_status                     0
last_contacted_date             0
number_of_contacts              0
last_contact_method          1326
sdr_owner                       0
utm_source                   1240
utm_medium                   1401
utm_campaign                 1389
email_opt_in                    0
phone_number                 2540
job_title                       0
notes                        7971
dtype: int64

In [46]:
industry_pct = (companies['industry'].isna().sum() / len(companies)) * 100
region_pct = (companies['region'].isna().sum() / len(companies)) * 100

In [47]:
region_pct

np.float64(0.9533537623425264)

In [48]:
industry_pct

np.float64(3.0303030303030303)

In [49]:
plan_tier = {


    'Starter': 'Starter',
    'STARTER': 'Starter',
    'starter': 'Starter',
    'Start': 'Starter',
    'Basic': 'Starter',
    'basic': 'Starter',


    'Growth': 'Growth',
    'GROWTH': 'Growth',
    'growth': 'Growth',
    'Grow': 'Growth',


    'Pro': 'Pro',
    'PRO': 'Pro',
    'pro': 'Pro',
    'Professional': 'Pro',
    'professional': 'Pro',


    'Enterprise': 'Enterprise',
    'ENTERPRISE': 'Enterprise',
    'enterprise': 'Enterprise',
    'ENT': 'Enterprise',
    'Ent': 'Enterprise',
    'Corp': 'Enterprise',
    'Scale': 'Enterprise'
}

deals['plan_tier'] = deals['plan_tier'].replace(plan_tier)

In [50]:
deals['plan_tier'].value_counts(dropna=False)

plan_tier
Enterprise    449
Starter       448
Pro           403
Growth        359
Name: count, dtype: int64

In [51]:
deals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   deal_id                1659 non-null   object
 1   lead_id                1659 non-null   object
 2   plan_tier              1659 non-null   object
 3   plan_id                1659 non-null   object
 4   deal_value_annual_usd  1610 non-null   float64
 5   close_date             1659 non-null   object
 6   loss_reason            833 non-null    object
 7   deal_stage             1659 non-null   object
 8   deal_probability_pct   1659 non-null   int64
 9   deal_type              1659 non-null   object
 10  deal_currency          1659 non-null   object
 11  expected_close_date    1659 non-null   object
 12  weighted_value_usd     1659 non-null   float64
 13  number_of_contacts     1659 non-null   int64
 14  competitor             1244 non-null   object
 15  discount_pct           1659 non-null   float64
 16  contract_type          1659 non-null   object
 17  next_step              1296 non-null   object
dtypes: float64(3), int64(2), object(13)
memory usage: 233.4+ KB

In [52]:
deals['close_date'] = pd.to_datetime(
    deals['close_date'],
     format='mixed',
    errors='coerce'
)

In [53]:
deals['close_date'].isna().sum()

np.int64(0)

In [54]:
deals['expected_close_date'] = pd.to_datetime(
    deals['expected_close_date']
)

In [55]:
import numpy as np

deals.loc[
    (deals['deal_value_annual_usd'] < 0) |
    (deals['deal_value_annual_usd'] > 2_400_000 ),
    'deal_value_annual_usd'
] = np.nan

In [56]:
deals['deal_value_annual_usd'].isna().sum()

np.int64(74)

In [57]:
deals['weighted_value_usd'] = (
    deals['deal_value_annual_usd'] *
    (deals['deal_probability_pct'] / 100)
)

In [58]:
deals.isna().sum()

deal_id                    0
lead_id                    0
plan_tier                  0
plan_id                    0
deal_value_annual_usd     74
close_date                 0
loss_reason              826
deal_stage                 0
deal_probability_pct       0
deal_type                  0
deal_currency              0
expected_close_date        0
weighted_value_usd        74
number_of_contacts         0
competitor               415
discount_pct               0
contract_type              0
next_step                363
dtype: int64

In [59]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871 entries, 0 to 870
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                871 non-null    object
 1   lead_id                    871 non-null    object
 2   contract_start_date        871 non-null    object
 3   contract_end_date          871 non-null    object
 4   contract_length_months     871 non-null    float64
 5   product_usage_score        871 non-null    float64
 6   nps_score                  871 non-null    float64
 7   mrr_usd                    871 non-null    float64
 8   arr_usd                    871 non-null    float64
 9   plan_tier                  826 non-null    object
 10  customer_success_rep       871 non-null    object
 11  health_score               871 non-null    int64
 12  health_status              871 non-null    object
 13  onboarding_status          871 non-null    object
 14  support_tier               871 non-null    object
 15  number_of_support_tickets  871 non-null    int64
 16  last_login_date            871 non-null    object
 17  expansion_revenue_usd      871 non-null    float64
 18  referrals_made             871 non-null    int64
 19  renewal_date               871 non-null    object
 20  auto_renew                 871 non-null    bool
dtypes: bool(1), float64(6), int64(3), object(11)
memory usage: 137.1+ KB

In [60]:
customers['contract_start_date'] = pd.to_datetime(
    customers['contract_start_date'],
     format='mixed',
    errors='coerce'
)

In [61]:
customers['renewal_date'].isna().sum()

np.int64(0)

In [62]:
customers['contract_end_date'] = pd.to_datetime(
    customers['contract_end_date'],
     format='mixed',
    errors='coerce'
)

In [63]:
customers['last_login_date'] = pd.to_datetime(
    customers['last_login_date']
)

In [64]:
customers['renewal_date'] = pd.to_datetime(
    customers['renewal_date'],
     format='mixed',
    errors='coerce'
)

In [65]:
customers['contract_length_months'] = customers['contract_length_months'].astype('Int64')

In [66]:
customers.describe()

,contract_start_date,contract_end_date,contract_length_months,product_usage_score,nps_score,mrr_usd,arr_usd,health_score,number_of_support_tickets,last_login_date,expansion_revenue_usd,referrals_made,renewal_date
count,871,871,871.0,871.000000,871.000000,871.000000,871.000000,871.000000,871.000000,871,871.000000,871.000000,871
mean,2023-09-16 03:39:53.111366400,2025-09-10 15:44:01.102181376,24.179104,56.163031,5.136625,4203.531975,50442.383697,37.933410,12.251435,2025-03-01 21:26:14.741676288,1210.946475,2.462687,2025-09-10 15:44:01.102181376
min,2022-01-08 00:00:00,2023-02-11 00:00:00,12.0,-5.000000,-1.000000,46.620000,559.440000,7.000000,0.000000,2022-04-16 00:00:00,0.000000,0.000000,2023-02-11 00:00:00
25%,2022-12-25 00:00:00,2024-10-27 12:00:00,12.0,32.000000,2.000000,752.205000,9026.460000,25.500000,6.000000,2024-07-27 12:00:00,0.000000,1.000000,2024-10-27 12:00:00
50%,2023-09-30 00:00:00,2025-10-05 00:00:00,24.0,55.000000,5.000000,2104.990000,25259.880000,37.000000,13.000000,2025-05-02 00:00:00,0.000000,2.000000,2025-10-05 00:00:00
75%,2024-06-05 00:00:00,2026-07-25 12:00:00,36.0,80.000000,8.000000,5678.185000,68138.220000,49.000000,19.000000,2025-12-04 12:00:00,611.650000,4.000000,2026-07-25 12:00:00
max,2025-10-03 00:00:00,2028-09-03 00:00:00,36.0,200.000000,15.000000,21843.680000,262124.160000,118.000000,25.000000,2026-06-23 00:00:00,9943.840000,5.000000,2028-09-03 00:00:00
std,NaN,NaN,9.719991,29.224711,3.281565,5005.110581,60061.326976,15.475458,7.400212,NaN,2485.363872,1.672130,NaN

In [67]:
customers.loc[
    (customers['product_usage_score'] < 0) |
    (customers['product_usage_score'] > 100 ),
    'product_usage_score'
] = np.nan

In [68]:
customers['health_score'].isna().sum()

np.int64(0)

In [69]:
print(customers[customers['product_usage_score'] > 100].shape[0])
print(customers[customers['product_usage_score'] < 0].shape[0])

0
0

In [70]:
customers.loc[
    (customers['nps_score'] < 0) |
    (customers['nps_score'] > 10 ),
    'nps_score'
] = np.nan

In [71]:
customers.loc[
    (customers['health_score'] > 100),
    'health_score'
] = np.nan

In [72]:
customers.isna().sum()

customer_id                   0
lead_id                       0
contract_start_date           0
contract_end_date             0
contract_length_months        0
product_usage_score          10
nps_score                    15
mrr_usd                       0
arr_usd                       0
plan_tier                    45
customer_success_rep          0
health_score                  5
health_status                 0
onboarding_status             0
support_tier                  0
number_of_support_tickets     0
last_login_date               0
expansion_revenue_usd         0
referrals_made                0
renewal_date                  0
auto_renew                    0
dtype: int64

In [73]:
missing_plan = customers[customers['plan_tier'].isna()]

missing_plan = missing_plan.merge(
    deals[['lead_id', 'plan_tier']],
    on='lead_id',
    how='left',
    suffixes=('_customer', '_deal')
)

missing_plan[['customer_id', 'lead_id', 'plan_tier_deal']].head()

  customer_id     lead_id plan_tier_deal
0  CUST-00008  LEAD-09138            NaN
1  CUST-00018  LEAD-06203            NaN
2  CUST-00054  LEAD-02677            NaN
3  CUST-00080  LEAD-05154            NaN
4  CUST-00088  LEAD-09968            NaN

In [74]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   churn_id               207 non-null    object
 1   customer_id            207 non-null    object
 2   churned                207 non-null    bool
 3   churn_date             207 non-null    object
 4   churn_reason           207 non-null    object
 5   days_to_churn          207 non-null    int64
 6   churn_type             207 non-null    object
 7   refund_issued          207 non-null    bool
 8   refund_amount_usd      207 non-null    float64
 9   exit_survey_completed  207 non-null    bool
 10  win_back_attempted     207 non-null    bool
 11  win_back_successful    207 non-null    bool
 12  final_mrr_usd          207 non-null    float64
 13  churned_arr_usd        207 non-null    float64
dtypes: bool(5), float64(3), int64(1), object(5)
memory usage: 15.7+ KB

In [75]:
churn['churn_date'] = pd.to_datetime(
    churn['churn_date'],
     format='mixed',
    errors='coerce'
)

In [76]:
churn['churn_date'].isna().sum()

np.int64(0)

In [77]:
churn.describe()

,churn_date,days_to_churn,refund_amount_usd,final_mrr_usd,churned_arr_usd
count,207,207.000000,207.000000,207.000000,207.000000
mean,2024-04-08 07:18:15.652173824,224.057971,852.477246,3663.678019,43964.136232
min,2022-04-14 00:00:00,-167.000000,0.000000,46.620000,559.440000
25%,2023-09-17 00:00:00,71.000000,0.000000,623.350000,7480.200000
50%,2024-05-03 00:00:00,171.000000,0.000000,1532.070000,18384.840000
75%,2024-12-16 12:00:00,325.000000,308.900000,4978.285000,59739.420000
max,2025-10-01 00:00:00,924.000000,18738.390000,21326.570000,255918.840000
std,NaN,198.738196,2442.901795,4668.373101,56020.477211

In [78]:
churn.loc[
    (churn['days_to_churn'] < 0),
    'days_to_churn'
] = np.nan

In [79]:
churn.isna().sum()

churn_id                 0
customer_id              0
churned                  0
churn_date               0
churn_reason             0
days_to_churn            1
churn_type               0
refund_issued            0
refund_amount_usd        0
exit_survey_completed    0
win_back_attempted       0
win_back_successful      0
final_mrr_usd            0
churned_arr_usd          0
dtype: int64

In [80]:
buyer.isna().sum()

evidence_id                             0
deal_id                                 0
last_confirmed_buyer_response_date      0
authority_engaged                       0
business_problem_confirmed              0
consequence_confirmed                   0
decision_timing_reconfirmed             0
buyer_owned_next_step                 175
next_step_date                          0
next_step_owner                       175
buyer_evidence_score                    0
dtype: int64

In [81]:
tables = {
    'churn': churn,
    'companies': companies,
    'customers': customers,
    'deals': deals,
    'leads': leads,
    'pricing': pricing,
    'buyer': buyer
}

for name, df in tables.items():
    df.to_csv(f'{name}_clean.csv', index=False)
    print(f'Saved {name}_clean.csv')

Saved churn_clean.csv
Saved companies_clean.csv
Saved customers_clean.csv
Saved deals_clean.csv
Saved leads_clean.csv
Saved pricing_clean.csv
Saved buyer_clean.csv

In [82]:
import os

os.listdir()

['.config',
 'churn_clean.csv',
 'leads_clean.csv',
 'customers_clean.csv',
 'companies_clean.csv',
 'buyer_clean.csv',
 'pricing_clean.csv',
 'drive',
 'deals_clean.csv',
 'sample_data']

In [83]:
from google.colab import files

files.download('buyer_clean.csv')